name: presmobile14

layers:
  scale1:
    type: rescale
    kwargs: {out_channels: 3, scale: 0.000390625, offset: 0}
  conv1:
    type: conv3x3
    kwargs: {out_channels: 16, strides: 1, padding: SAME, groups: 1}
  pool1:
    type: maxpool2x2
    kwargs:
  conv2:
    type: resmobile3x3
    kwargs: {out_channels: 32, strides: 1}
  pool2:
    type: maxpool2x2
    kwargs:
  conv3:
    type: resmobile3x3
    kwargs: {out_channels: 64, strides: 1}
  pool3:
    type: maxpool2x2
    kwargs:
  conv4:
    type: resmobile3x3
    kwargs: {out_channels: 128, strides: 1}
  pool4:
    type: maxpool2x2
    kwargs:
  conv5:
    type: resmobile3x3
    kwargs: {out_channels: 256, strides: 1}
  conv6:
    type: resmobile3x3
    kwargs: {out_channels: 256, strides: 1}
  pool5:
    type: maxpool2x2
    kwargs:
  conv7:
    type: resmobile3x3
    kwargs: {out_channels: 512, strides: 1}
  gap1:
    type: pyramid_gap
    in_layers: [pool2, pool3, pool4, conv7]
    kwargs: {out_channels: 736}
